### ISSUE TITLE
DNS - ERROR Failed to add TXT record: error="no response received"

### ISSUE THREAD

**Issue by robertpenz** [hm-edu/harica#43]
I've configured 

```
zones:
  - domain: "domain."
    nameserver: "127.0.0.1:5353"
    tsig_key_name: "xxxxx"
    tsig_secret: "xxxxxxx"
    sig_secret_alg: "hmac-sha512."
    net: "tcp"
```

and I get 

```
2025/03/27 15:27:41 ERROR Failed to add TXT record: error="no response received"
2025/03/27 15:27:41 ERROR Failed to validate domain: error="no response received"
```

If I take a look at it with WireGuard I see the following, so a TCP connection is established, but the client does not send anything.

![Image](https://github.com/user-attachments/assets/861a0079-70d9-4924-91db-aae3e3b7b4c6)

Can I also have debug code here? :-)
